movies/urls.py
from django.urls import path
from . import views

# namespace
app_name = 'movies'

# movies/
# movies/1/details

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie
# Create your models here.


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        # omit attribute
        excludes = ['date_created']

movies/models.py
from django.db import models
from django.utils import timezone
# Connect MongoDB using Djongo here https://nesdis.github.io/djongo/get-started/
# Create your models here.
# Inheritance


class Genre(models.Model):
    # keyword arguments
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Movie

# Create your views here.


def index(req):
    movies = Movie.objects.all()
    output = ', '.join([m.title for m in movies])
    # return HttpResponse(output)

    # return HTML template with workspace
    return render(req, 'movies/index.html', {'movies': movies})


def detail(req, movie_id):
    # way 1 to render the template
    # try:
    #     movie = Movie.objects.get(pk=movie_id)
    #     return render(req, 'movies/detail.html', {'movie': movie})
    # except Movie.DoesNotExist:
    #     raise Http404()

    # way 2 to render template
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(req, 'movies/detail.html', {'movie': movie})

vidly/views.py
from django.shortcuts import render, get_object_or_404


def home(req):
    return render(req, 'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<dl>
  <dt>Title</dt>
  <dd>{{ movie.title }}</dd>
  <dt>Genre</dt>
  <dd>{{ movie.genre }}</dd>
  <dt>Stock</dt>
  <dd>{{ movie.number_in_stock }}</dd>
</dl>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Stock</th>
      <th>Daily Rate</th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movies %}
    <tr>
      <td>
        <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a>
      </td>
      <td>{{ movie.genre }}</td>
      <td>{{ movie.number_in_stock }}</td>
      <td>{{ movie.daily_rate }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <title>Vidly</title>
</head>

<body>
  <!-- As a link -->
  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#">Vidly</a>
  </nav>

  <main class="container">
    {% block content %}
    {% endblock %}
  </main>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

  <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'movies:index' %}">Movies</a>

{% endblock %}